# Generated by Django 5.1.1 on 2024-11-20 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "custom_auth_group",
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "custom_auth_user",
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id_category",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=500)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "custom_django_session",
            },
        ),
        migrations.CreateModel(
            name="Docgias",
            fields=[
                (
                    "id_docgia",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=255)),
                ("gender", models.IntegerField()),
                ("birthday", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("ngay_tao", models.CharField(max_length=50)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "docgias",
            },
        ),
        migrations.CreateModel(
            name="Kiemkes",
            fields=[
                (
                    "id_kiemke",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ngay_tao", models.CharField(max_length=50)),
                ("ly_do", models.CharField(max_length=255)),
                ("file_kiemke", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "kiemkes",
            },
        ),
        migrations.CreateModel(
            name="Phieuhuys",
            fields=[
                (
                    "id_phieuhuy",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ngay_huy", models.CharField(max_length=50)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "phieuhuys",
            },
        ),
        migrations.CreateModel(
            name="Phieunhaps",
            fields=[
                (
                    "id_phieunhap",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("donvi_cungcap", models.CharField(max_length=255)),
                ("ngay_nhap", models.CharField(max_length=50)),
                ("ly_do_nhap", models.CharField(max_length=255)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "phieunhaps",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id_user",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("role", models.IntegerField()),
                ("gender", models.IntegerField()),
                ("birthday", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id_sach",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("image", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=100)),
                ("is_delete", models.BooleanField(default=False)),
                ("ngay_tao", models.CharField(max_length=50)),
                (
                    "id_category",
                    models.ForeignKey(
                        db_column="id_category",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.categories",
                    ),
                ),
            ],
            options={
                "db_table": "books",
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "custom_django_content_type",
                "unique_together": {("app_label", "model")},
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="books.authuser",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="books.djangocontenttype",
                    ),
                ),
            ],
            options={
                "db_table": "custom_django_admin_log",
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="books.djangocontenttype",
                    ),
                ),
            ],
            options={
                "db_table": "custom_auth_permission",
                "unique_together": {("content_type", "codename")},
            },
        ),
        migrations.CreateModel(
            name="Ctkiemkes",
            fields=[
                (
                    "id_ctkiemke",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("so_luong_kiemke", models.IntegerField()),
                ("so_luong_bandau", models.IntegerField()),
                (
                    "id_sach",
                    models.ForeignKey(
                        db_column="id_sach",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.books",
                    ),
                ),
                (
                    "id_kiemke",
                    models.ForeignKey(
                        db_column="id_kiemke",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.kiemkes",
                    ),
                ),
            ],
            options={
                "db_table": "ctkiemkes",
            },
        ),
        migrations.CreateModel(
            name="Ctphieuhuys",
            fields=[
                (
                    "id_ctphieuhuy",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("so_luong", models.IntegerField()),
                ("ly_do_huy", models.CharField(max_length=500)),
                (
                    "id_sach",
                    models.ForeignKey(
                        db_column="id_sach",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.books",
                    ),
                ),
                (
                    "id_phieuhuy",
                    models.ForeignKey(
                        db_column="id_phieuhuy",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.phieuhuys",
                    ),
                ),
            ],
            options={
                "db_table": "ctphieuhuys",
            },
        ),
        migrations.CreateModel(
            name="Ctphieunhaps",
            fields=[
                (
                    "id_ctphieunhap",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("so_luong", models.IntegerField()),
                ("gia_nhap", models.FloatField()),
                (
                    "id_sach",
                    models.ForeignKey(
                        db_column="id_sach",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.books",
                    ),
                ),
                (
                    "id_phieunhap",
                    models.ForeignKey(
                        db_column="id_phieunhap",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.phieunhaps",
                    ),
                ),
            ],
            options={
                "db_table": "ctphieunhaps",
            },
        ),
        migrations.CreateModel(
            name="Thethuviens",
            fields=[
                (
                    "id_the",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("type", models.IntegerField()),
                ("ngay_tao", models.CharField(max_length=50)),
                ("ngay_het_han", models.CharField(max_length=50)),
                ("ghi_chu", models.CharField(max_length=255)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "id_docgia",
                    models.ForeignKey(
                        db_column="id_docgia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.docgias",
                    ),
                ),
            ],
            options={
                "db_table": "thethuviens",
            },
        ),
        migrations.AddField(
            model_name="phieunhaps",
            name="id_user",
            field=models.ForeignKey(
                db_column="id_user",
                on_delete=django.db.models.deletion.CASCADE,
                to="books.users",
            ),
        ),
        migrations.CreateModel(
            name="Phieumuons",
            fields=[
                (
                    "id_phieumuon",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ngay_tao", models.CharField(max_length=50)),
                ("ngay_hen_tra", models.CharField(max_length=50)),
                ("trang_thai", models.IntegerField()),
                ("ngay_tra", models.CharField(max_length=50)),
                ("ghi_chu", models.CharField(max_length=255)),
                ("so_luong", models.IntegerField()),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "id_sach",
                    models.ForeignKey(
                        db_column="id_sach",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.books",
                    ),
                ),
                (
                    "id_the",
                    models.ForeignKey(
                        db_column="id_the",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.thethuviens",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        db_column="id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.users",
                    ),
                ),
            ],
            options={
                "db_table": "phieumuons",
            },
        ),
        migrations.AddField(
            model_name="phieuhuys",
            name="id_user",
            field=models.ForeignKey(
                db_column="id_user",
                on_delete=django.db.models.deletion.CASCADE,
                to="books.users",
            ),
        ),
        migrations.AddField(
            model_name="kiemkes",
            name="id_user",
            field=models.ForeignKey(
                db_column="id_user",
                on_delete=django.db.models.deletion.CASCADE,
                to="books.users",
            ),
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.authgroup",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.authpermission",
                    ),
                ),
            ],
            options={
                "db_table": "custom_auth_group_permissions",
                "unique_together": {("group", "permission")},
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.authgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.authuser"
                    ),
                ),
            ],
            options={
                "db_table": "custom_auth_user_groups",
                "unique_together": {("user", "group")},
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.authpermission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.authuser"
                    ),
                ),
            ],
            options={
                "db_table": "custom_auth_user_user_permissions",
                "unique_together": {("user", "permission")},
            },
        ),
    ]
